experiment: ???
run_dir: ./logs/${experiment}/${now:%Y-%m-%d_%H-%M-%S_%f}

hydra:
  run:
    dir: ${run_dir}

prompt_generator:
  task: ${task}
  retriever: ${retriever}
  num_retrieve: ${num_retrieve}
  max_length: 2048

llm:
  task: ${task}
  model: meta-llama/Meta-Llama-3-8B-Instruct
  provider: local
  # model: gpt-4o-mini
  # provider: openai
  # model: meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
  # provider: together
  generate_kwargs:
    max_new_tokens: 256
    do_sample: true
    num_beams: 1
    temperature: 0.6
    top_p: 0.9

seed: 0
task: ???
num_retrieve: 5
