defaults:
  - llm: ???
  - _self_

experiment: debug
run_dir: ./logs/${experiment}/${now:%Y-%m-%d_%H-%M-%S_%f}

hydra:
  run:
    dir: ${run_dir}

prompt_generator:
  max_length: 2048

seed: 42
task: ???
num_retrieve: ???
