defaults:
  - llm: phi-4-mini-instruct
  - _self_

exp_name: debug
run_dir: ./logs/${exp_name}/${now:%Y-%m-%d_%H-%M-%S_%f}

hydra:
  run:
    dir: ${run_dir}

prompt_generator:
  max_length: 2048

seed: 42
task: ???
num_retrieve: 5
