experiment: ???
run_dir: ./outputs/${experiment}/${now:%Y-%m-%d_%H-%M-%S_%f}

hydra:
  run:
    dir: ${run_dir}

defaults:
  - _self_
  - generation: ???

seed: 0             # Seed that controls all sources of randomness
task: ???           # LaMP task (LaMP-6 not supported)
n_retrieve: 5       # Number of retrieved profiles per question
